config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'book#index'
  get 'libros/todos', to: 'book#index'
  get 'libros/nuevo', to: 'book#new'
  post 'libros/crear', to: 'book#create'
  get 'libros/mostrar/:id', to: 'book#show'
  post 'libros/borrar/:id', to: 'book#delete'
  get 'libros/editar/:id', to: 'book#show_edit'
  post 'libros/edit/:id', to: 'book#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :delete]

    def index
        @books = Book.all
    end

    def new
        @authors = Author.all
    end

    def create
        book_params = params.require(:book).permit(:title, :description, :author_id)
        Book.create(book_params)
        redirect_to action: 'index'
    end

    def show
        @book = Book.find(params[:id])
        @author = Author.find(@book.author_id)
        if @book.nil?
            redirect_to action: 'index'
        end
    end

    def delete
        @book = Book.find(params[:id])
        unless @book.nil?
            @book.delete
        end

        redirect_to action: 'index'
    end

    def show_edit
        @book = Book.find(params[:id])
        @authors = Author.all
        if @book.nil?
            redirect_to action: 'index'
        end
    end

    def edit
        @book = Book.find(params[:id])
        book_params = params.require(:book).permit(:title, :description, :author_id)
        if @book.nil?
            redirect_to action: 'index'
        end

        @book.update(book_params)
        redirect_to action: 'show'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/index.html.erb
<h2> Libros </h2>
<ul>
    <% for book in @books%>
    <li>
    <a href="/libros/mostrar/<%= book.id %>">
        <%= book.title %>
    </a>
    </li>
    <% end %>
</ul>

<a href="/libros/nuevo"> <h2> Crear nuevo libro </h2> </a>

app/views/book/new.html.erb
<h3>Crear libro</h3>
<form method="post" action="<%= libros_crear_path %>">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div>
    <label>Nombre </label>
    <br>
    <input type="text" placeholder="Ingrese el nombre" name="book[title]" >
    </div>
    <div>
    <label>Descripcion </label>
    <br>
    <textarea name="book[description]"></textarea>
    </div>
    <div>
    <label> Autor </label>
    <br>
    <select name="book[author_id]">
        <% for author in @authors%>
        <option  value="<%= author.id%>">  <%= author.name %> </option>
        <% end %>
    </select>
    </div>
    <div>
        <button type="submit">Crear</button>
    </div>
</form>

app/views/book/show.html.erb
<h2> <%=@book.title%> </h2>
<p><%= @book.description %></p>
<h2> Autor: <%= @author.name %> </h2>
<form method="post" action="/libros/borrar/<%= @book.id%>" >
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button type="submit"> Borrar </button>
</form>
<form method="get" action="/libros/editar/<%= @book.id%>" >
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button type="submit"> Editar </button>
</form>

app/views/book/show_edit.html.erb
<h3>Editar libro</h3>
<form method="post" action="/libros/edit/<%= @book.id%>" >
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div>
    <label>Nombre </label>
    <br>

    <input type="text" value="<%=@book.title%>" name="book[title]" >
    </div>
    <div>
    <label>Descripcion </label>
    <br>
    <textarea name="book[description]"><%= @book.description %></textarea>
    </div>
     <div>
    <label> Autor </label>
    <br>
    <select name="book[author_id]">
        <% for author in @authors%>
        <option  value="<%= author.id%>">  <%= author.name %> </option>
        <% end %>
    </select>
    </div>

    <div>
        <button type="submit">Editar</button>
    </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div>
        <h3> Hola <%= current_user.email %> </h3>
        <a style="float: right" href="<%= destroy_user_session_path %>" data-method="delete"> Cerrar sesión </a>
    </div>
    <% else %>
    <a href="<%= new_user_session_path %>"> Iniciar sesión </a>
    <a href="<%= new_user_registration_path %>"> Registrarse </a>
    <% end %>

    <%= yield %>
  </body>
</html>